version: '3'
services:
  php-fpm:
    build: ./docker/php
    image: bingo/bingo:php-fpm
    restart: on-failure
    container_name: bingo-php-fpm
    command: php-fpm
    volumes:
      - ./:/bingo
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 9000 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build: ./docker/nginx
    image: bingo/bingo:nginx
    restart: on-failure
    container_name: bingo-nginx
    command: nginx -g "daemon off;"
    links:
      - php-fpm
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/bingo
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 80 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2